import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { symbol } from 'prop-types'
import { getAllPosts } from '@/utils/api'
import { Cat } from '@/utils/Types'
import Link from 'next/link'

type Props = {
  cats: Cat [];
};

export async function getStaticProps() {
  const cats: Cat[] = await getAllPosts();

  return {
    props: {
      cats,
    },
  };
}

export default function Home({ cats }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>mochi blog</h1>
        <ul className={styles.postList}>
          {cats.map((cat: Cat) => (
            <Link href={`/${cat.name}`} key={cat.name}>
              <li className={styles.post}>
                <h2 className={styles.title}>{cat.name}</h2>
                <p className={styles.author}>{cat.breed}</p>
              </li>
            </Link>
          ))}
          
        </ul>
      </div>
    </>
  )
}
